apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  containers:
    - name: node-app
      image: tzumby/node-web-app:1.0.0
      ports:
        - name: http
          containerPort: 8080
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
    - name: node-health
      image: tzumby/node-health:latest
      ports:
        - name: health
          containerPort: 8081
      livenessProbe:
        httpGet:
          path: /health
          port: 8081
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 15
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8081
          scheme: HTTP
        initialDelaySeconds: 5
        timeoutSeconds: 1
      
